version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: autentica-o_flask-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: flask-crud
      MYSQL_USER: admin
      MYSQL_PASSWORD: "123"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
